name: Prueba Actions

on:
  push:
    branches:
      - main
      - dev

jobs:
  hello:
    name: Test Actions Hello
    runs-on: ubuntu-20.04
    steps:
      - name: Hola
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm test
      - run: echo proceso terminado
