name: Prueba Actions

on:
  push:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Test Actions Suma
    runs-on: ubuntu-20.04
    steps:
      - name: Chechout
        uses: actions/checkout@dev
#      - run: npm install
#      - run: npm test
        run: echo proceso terminado
